### ISSUE TITLE
Issues from the old repo

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-tiledmenu#1]
* [ ] [Not an issue proper](https://github.com/Zren/plasma-applets/issues/125)
* [x] [How to change background of tiles?](https://github.com/Zren/plasma-applets/issues/120)
* [ ] [Hover over sidebar, Highlight disappears](https://github.com/Zren/plasma-applets/issues/114)
* [ ] [Add to panel (widget)](https://github.com/Zren/plasma-applets/issues/113)
* [ ] [Widget Tiles, Resize with LeftMouseButton, Tile Folders, Groups/Labels](https://github.com/Zren/plasma-applets/issues/99)
* [ ] [You can add widgets on it Tile section, but they dont work](https://github.com/Zren/plasma-applets/issues/87)
* [ ] [Panel icon doesn't respect size](https://github.com/Zren/plasma-applets/issues/85)
* [ ] [Installing this in Linux Mint KDE (Plasma 5.8.5)](https://github.com/Zren/plasma-applets/issues/77)
* [ ] [some ideas](https://github.com/Zren/plasma-applets/issues/67)
* [ ] [Sidebar directories like ~/Music need to be localized](https://github.com/Zren/plasma-applets/issues/65)
* [x] [Shows applications before desktop search](https://github.com/Zren/plasma-applets/issues/55)
* [x] [TiledMenu does not work with git master (Plasma 5.9)](https://github.com/Zren/plasma-applets/issues/52)
* [x] [TiledMenu Suggestions](https://github.com/Zren/plasma-applets/issues/45)

Translations

* [Spanish](https://github.com/Zren/plasma-applets/pull/88)
* [Chinese](https://github.com/Zren/plasma-applets/pull/75) ([2](https://github.com/Zren/plasma-applets/issues/53))
* [German](https://github.com/Zren/plasma-applets/pull/54)
*
